version: '3.5'
services:
  web:
    container_name: somecomix
    hostname: somecomix
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/fonte
    ports:
      - 3000:3000